
PROJECT	= xmilnds

OBJBASE	=	../obj
BINBASE	=	../bin

OBJ		=	$(OBJBASE)/$(PROJECT)
BIN		=	$(BINBASE)/xmilnds

AOPT9	=	--defsym MAKESCRN_VRAMFF=1
COPT9	=	-DMAKESCRN_VRAMFF=1

#AOPT7	=
#COPT7	=

NDSROM	=	$(BIN)/$(PROJECT).nds

include Makefile.inc

